"""
85-class Indian Traffic Sign label map.
Dataset: kannanwisen/Indian-Traffic-Sign-Classification
"""

CLASS_NAMES: dict[int, str] = {
    0:  "All Motor Vehicles Prohibited",
    1:  "Axle Load Limit",
    2:  "Barrier Ahead",
    3:  "Bullock and Handcart Prohibited",
    4:  "Bullock Prohibited",
    5:  "Cattle",
    6:  "Compulsory Ahead",
    7:  "Compulsory Ahead or Turn Left",
    8:  "Compulsory Ahead or Turn Right",
    9:  "Compulsory Cycle Track",
    10: "Compulsory Keep Left",
    11: "Compulsory Keep Right",
    12: "Compulsory Minimum Speed",
    13: "Compulsory Sound Horn",
    14: "Compulsory Turn Left",
    15: "Compulsory Turn Left Ahead",
    16: "Compulsory Turn Right",
    17: "Compulsory Turn Right Ahead",
    18: "Cross Road",
    19: "Cycle Crossing",
    20: "Cycle Prohibited",
    21: "Dangerous Dip",
    22: "Direction",
    23: "Falling Rocks",
    24: "Ferry",
    25: "Gap in Median",
    26: "Give Way",
    27: "Guarded Level Crossing",
    28: "Handcart Prohibited",
    29: "Height Limit",
    30: "Horn Prohibited",
    31: "Hump or Rough Road",
    32: "Left Hair Pin Bend",
    33: "Left Hand Curve",
    34: "Left Reverse Bend",
    35: "Left Turn Prohibited",
    36: "Length Limit",
    37: "Load Limit",
    38: "Loose Gravel",
    39: "Men at Work",
    40: "Narrow Bridge",
    41: "Narrow Road Ahead",
    42: "No Entry",
    43: "No Parking",
    44: "No Stopping or Standing",
    45: "Overtaking Prohibited",
    46: "Pass Either Side",
    47: "Pedestrian Crossing",
    48: "Pedestrian Prohibited",
    49: "Priority for Oncoming Vehicles",
    50: "Quay Side or River Bank",
    51: "Restriction Ends",
    52: "Right Hair Pin Bend",
    53: "Right Hand Curve",
    54: "Right Reverse Bend",
    55: "Right Turn Prohibited",
    56: "Road Widens Ahead",
    57: "Roundabout",
    58: "School Ahead",
    59: "Side Road Left",
    60: "Side Road Right",
    61: "Slippery Road",
    62: "Speed Limit 15",
    63: "Speed Limit 20",
    64: "Speed Limit 30",
    65: "Speed Limit 40",
    66: "Speed Limit 5",
    67: "Speed Limit 50",
    68: "Speed Limit 60",
    69: "Speed Limit 70",
    70: "Speed Limit 80",
    71: "Staggered Intersection",
    72: "Steep Ascent",
    73: "Steep Descent",
    74: "Stop",
    75: "Straight Prohibited",
    76: "Tonga Prohibited",
    77: "Traffic Signal",
    78: "Truck Prohibited",
    79: "Turn Right",
    80: "T Intersection",
    81: "Unguarded Level Crossing",
    82: "U-Turn Prohibited",
    83: "Width Limit",
    84: "Y Intersection",
}
